### ISSUE TITLE
Build Instructions?

### ISSUE THREAD

**Issue by ghost** [a-ignatov-parc/tvos-soap4.me#1]
Hai, any instructions on how to build this project?

**Comment by a-ignatov-parc** [comment]
Hi there. Not yet because it's in active development and I haven't found time for the documentation. But I will be able to write short instruction on this weekends if you are interested in.

By the way it's a demo project for testing [tvdml](https://github.com/a-ignatov-parc/tvdml) library. It's for writing tvOS apps in javascript using TVML and TVJS. It doesn't have any documentation too but I hope you can understand the basics from this two files: [this](https://github.com/a-ignatov-parc/tvos-soap4.me/blob/master/src/index.js#L15-L49) and [this](https://github.com/a-ignatov-parc/tvos-soap4.me/blob/master/src/routes/all.js).

**Comment by a-ignatov-parc** [comment]
Also if you have any questions feel free to ask

**Comment by hessius** [comment]
I can't figure out how to build this project (though the basics of tvdml looks very readable!)

**Comment by a-ignatov-parc** [comment]
There are some short instructions in https://github.com/a-ignatov-parc/tvos-soap4.me/issues/2#issuecomment-239640490. But i haven't got time to write a normal readme. Sorry guys.
